import type { NextPage, GetStaticProps } from 'next'
import type {AppProps} from 'next/app'
import Head from 'next/head'
import Image from 'next/image'
import Articles from '../components/Articles'
import Layout from '../components/Layout'
import styles from '../styles/Layout.module.css'

interface Props {
  articles?: any[]
}

const Home: NextPage<Props> = ({articles}) => {

  return (
    <>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <h1>Welcome to Next.js</h1>
        <Articles articles={articles}/>
    </>
  )
}

export default Home

export const getStaticProps: GetStaticProps = async () => {
  const res = await fetch(`https://jsonplaceholder.typicode.com/posts?_limit=6`)

  const articles = await res.json()

  return {
    props: {
      articles
    }
  }
}

